/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
    },
    extend: {
      fontFamily: {
        sans: ['var(--rxst-font-sans)'],
        mono: ['var(--rxst-font-mono)'],
        headline: ['SF Pro Display Bold'],
        headline2: ['Satoshi'],
      },
      colors: {
        'stakebar-1': '#6B43EE',
        'stakebar-2': '#ce5fff',
        'observatory-1': '#2FB3A3',
        'observatory-2': '#5bc0b4',
        'sdp-1': '#3A61F9',
        'sdp-2': '#3aa3f9',
        'about-1': '#2D3748',
        'about-2': '#4479ec',
        'croco-1': '#34A13C',
        'croco-2': '#8fbe20',
        'trezor-1': '#000000',
        'trezor-2': '#03854D',
        'duo-1': '#238CE5',
        'duo-2': '#4ebbf2',
        'eigen-1': '#150958',
        'eigen-2': '#4a63e8',
        'wormhole-1': '#000000',
        'wormhole-2': '#000000',
        'mayan-1': '#49a9f1',
        'mayan-2': '#3885FF',
        'text-1': '#2D3748',
        'text-2': '#606d81',
        'text-3': '#CBD5E0',
      },
    },
  },
  plugins: [],
};
