export enum Project {
  RobertBrada = 'Robert Brada',
  StakeBar = 'StakeBar',
  SDP = 'Smart Delegation App',
  Observatory = 'Observatory',
  CrocoFinance = 'Croco Finance',
  Trezor = 'Trezor',
  Eigen = 'EigenBeat',
  Wormhole = 'Wormhole',
  Mayan = 'Mayan Swap',
  BlinkMate = 'BlinkMate',
  PromptBar = 'PromptBar',
  MacAway = 'MacAway',
  // Spark = "Spark",
}
